{% set version = "0.7.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinyfiles
  version: {{ version|replace("-", "_") }}

source:
  fn: shinyFiles_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/shinyFiles_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/shinyFiles/shinyFiles_{{ version }}.tar.gz

  sha256: a5bd53a9b3332212dc33c8de24cca12875d4c1012524695e7ee2749378968c36

build:
  noarch: generic
  number: 1000

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-fs >=1.2.6
    - r-htmltools
    - r-jsonlite
    - r-shiny >=1.1.0
    - r-tibble >=1.4.2

  run:
    - r-base
    - r-fs >=1.2.6
    - r-htmltools
    - r-jsonlite
    - r-shiny >=1.1.0
    - r-tibble >=1.4.2

test:
  commands:
    - $R -e "library('shinyFiles')"  # [not win]
    - "\"%R%\" -e \"library('shinyFiles')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shinyFiles
  license: GPL (>= 2)
  summary: Provides functionality for client-side navigation of the server side file system in
    shiny apps. In case the app is running locally this gives the user direct access
    to the file system without the need to "download" files to a temporary location.
    Both file and folder selection as well as file saving is available.
  license_family: GPL3
extra:
   recipe-maintainers:
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
