travis:
  secure:
    BINSTAR_TOKEN: PKKUoVdoGueqk8eFQIabc4V6bR0PqDPWj0/VdvKIdsoVOcgM0tiFbVqbRLdPzSPRAFQoUIj/XU7tc/FoBqUXJ9Tu7vMrh4diIGCwkmIkj2lNKa1EjJHUxMjJYOj1r0tGmWeWjbCGJBg91AXAl77gfoMy08BfQhdymTCG5pnGWmm92koyiBTSedm7rFC9c/KGaAmezt2++xVuCNgTCFZ0JXFig/XRHBu9ZUQISLVSHClBIeJatK1plMF6QNg+3nRZGNma/D/8IBf6R6Gb129bl8l9+MFbDE1AWUnOeA/c5AYQFQFCmhMK5nawaneRtkDVnYYFt2GxncAdU0hTe3Uu3quFtNdGKDvrq1u90uqP4eeOSq6kL3r+aCpPxmoidWgk9DOxVmEtAgb6biSH/JxvTQvFfqXCiKNiLgwDstp+pu0vt3MHWcg6RKNNLMLMEmwl4JVx/IFztsDobUHTPi+yFk6jYswBnb4Iiz0nWj8t9CThtSFRnhqIuWd5xdOJ7JFbcRTT9ghxQN+RZuXFV8PlXd9EBXGya6F42vDyUVKTsZAWCNNvWcuX1bzkzjl7MFGeABixLDaAn13U/17HXNkoOy9DTixwM3SRhf/2gZU2iTlgM3czqvy1E/dxXYBOgXY2TPcCvMcrZ2iGd7er1jv/y2LujsayBvpPvFPieFPpd6A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
