travis:
  secure:
    BINSTAR_TOKEN: CTUBltZbJn8Rmqkk32yoOGT97MCMV74QqfhM8t3qmAo3XCNAnzMf6nKexDBbUYVv5a0HYozBQQHmC3D4HcjjxZNpy0F4liyVOtPq8MunOfRIt4WVdgwrC6c0lAMOFPUeiFr6+aewT/RGja/Bgw5J64Wf+9ZXxwtGvT2p8sCOjdqEtK7M6lWNmBHstsXdY70nV/AYZpQ8dddQgNBra2yAV0LCbFRU9qjCAm20b0mBZtxvFU009bAZTxuCDxuay/iWK7dgZ1NB1jpfso88pX/SUenesjMjcT97gHKB5SovGARtEOtaRqTtjy6aos3Vp17AQaZvUSUV6twdQOFis+uJpK8Fh9E7BlYEFLtaIGKYWkwix6leP3s0j9OwVfo7ErL87c87FPobONcV5qd+fjE18vUhO/l0SHqYHaQEHzBwNmYzy10zzoVB6bjnzeVRXMT/aRQwAQBmq7avWusnVjKUW8cW8yzxWM/OqT+XOrS1O0p6KP7HkI6V+l81wP7bd+TljnWCSoAm85KiBljTVa2zVFTq1Ujv4GaeTBfs8qPN+i4PnlDdnsshiy+RkTGZbyGN4Kv42hkF0LmTOLy+73TsRpUCDFhl52omKDuHyzqD0wc6Dw8jkUSWLeaTlztATUsm13JfpECKTRj6kEqtBUGBCauoWsli9TTGyAOcYjI8mV8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
